name: Cypress tests script
on: [push]
jobs:
 cypress-run:
  runs-on: ubuntu-latest
  steps:
  - name: Checkout
    uses: actions/checkout@v1
  - name: Setup npm package
    run: npm init -y && npm install
  - name: Cypress run
    uses: cypress-io/github-action@v1
    env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
