ame:  Cypress Tests

on: [push]

jobs:
test:
name: Cypress run
runs-on: ubuntu-latest

steps:
- name: Checkout
uses: actions/checkout@v2

# because of "record" and "parallel" parameters
# these machines will load balance all found tests among themselves
- name: Cypress run
uses: cypress-io/github-action@v2
with:
record: true
group: 'Actions example'
env:
# pass the Dashboard record key as an environment variable
CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
